const toEntries = (names: string[], unilateral: boolean) =>
	[...new Set(names)].map((name) => ({ name, unilateral }));

const BILATERAL_EXERCISE_NAMES = [
	// Pulling
	'Pull-up',
	'Weighted Pull-up',
	'Wide Grip Pull-up',
	'Neutral Grip Pull-up',
	'Chin-up',
	'Weighted Chin-up',
	'Sternum Pull-up',
	'Ring Pull-up',
	'Scap Pull-up',
	'Assisted Pull-up',
	'Band Assisted Pull-up',
	'Rack Chin',
	'Lat Pulldown',
	'Wide Grip Lat Pulldown',
	'Medium Grip Lat Pulldown',
	'Close Grip Lat Pulldown',
	'Close Neutral Lat Pulldown',
	'Close Supinated Lat Pulldown',
	'Underhand Lat Pulldown',
	'Pronated Lat Pulldown',
	'MAG Grip Lat Pulldown',
	'Behind the Neck Lat Pulldown',
	'Lat Prayer',
	'Straight Arm Pulldown',
	'Rope Straight Arm Pulldown',
	'Straight Arm Pressdown',
	'Cable Pullover',
	'Rope Cable Pullover',
	'Machine Pullover',
	'Nautilus Pullover',
	'Dumbbell Pullover',
	'Barbell Pullover',
	'Bent Over Barbell Row',
	'Overhand Barbell Row',
	'Underhand Barbell Row',
	'Pendlay Row',
	'Yates Row',
	'T-Bar Row',
	'Chest Supported T-Bar Row',
	'Landmine Row',
	'Seal Row',
	'Chest Supported Barbell Row',
	'Chest Supported Dumbbell Row',
	'Chest Supported Machine Row',
	'Machine Row',
	'Iso Lateral Row',
	'Plate Loaded Row',
	'Seated Cable Row',
	'Wide Grip Seated Cable Row',
	'Close Neutral Cable Row',
	'Underhand Seated Cable Row',
	'Rope Seated Cable Row',
	'Upper Back Cable Row',
	'Lat Bias Cable Row',
	'High Row',
	'Low Row',
	'Machine High Row',
	'Machine Low Row',
	'Chest Supported High Row',
	'Chest Supported Low Row',
	'Upper Back Chest Supported Row',
	'Lat Bias Chest Supported Row',
	'Smith Machine Row',
	'Inverted Row',
	'Suspension Row',
	'Ring Row',
	'Towel Row',
	'Rear Delt Row',
	'Wide Elbow Row',
	'Face Pull',
	'Rope Face Pull',
	'Cable Face Pull',
	'Face Pull External Rotation',
	'Kelso Shrug',
	'Scapular Pulldown',
	'Scapular Pull-up',
	'Barbell Shrug',
	'Dumbbell Shrug',
	'Smith Shrug',
	'Trap Bar Shrug',

	// Chest / pressing
	'Barbell Bench Press',
	'Paused Barbell Bench Press',
	'Touch and Go Bench Press',
	'Close Grip Bench Press',
	'Medium Grip Bench Press',
	'Wide Grip Bench Press',
	'Spoto Press',
	'Pin Press',
	'Board Press',
	'Larsen Press',
	'Feet Up Bench Press',
	'Guillotine Press',
	'Swiss Bar Bench Press',
	'Football Bar Bench Press',
	'Incline Barbell Bench Press',
	'Low Incline Barbell Bench Press',
	'High Incline Barbell Bench Press',
	'Decline Barbell Bench Press',
	'Smith Bench Press',
	'Smith Incline Press',
	'Smith Decline Press',
	'Machine Chest Press',
	'Plate Loaded Chest Press',
	'Converging Chest Press',
	'Flat Machine Chest Press',
	'Incline Machine Chest Press',
	'Decline Machine Chest Press',
	'Horizontal Chest Press',
	'Dumbbell Bench Press',
	'Dumbbell Incline Press',
	'Dumbbell Low Incline Press',
	'Dumbbell High Incline Press',
	'Dumbbell Decline Press',
	'Dumbbell Floor Press',
	'Dumbbell Squeeze Press',
	'Hex Press',
	'Svend Press',
	'Push-up',
	'Deficit Push-up',
	'Weighted Push-up',
	'Ring Push-up',
	'Parallette Push-up',
	'Dip',
	'Weighted Dip',
	'Chest Dip',
	'Ring Dip',
	'Machine Dip',
	'Cable Press',
	'Dual Cable Press',
	'Pec Deck',
	'Butterfly Machine Fly',
	'Machine Fly',
	'Flat Machine Fly',
	'Incline Machine Fly',
	'Decline Machine Fly',
	'Flat Dumbbell Fly',
	'Incline Dumbbell Fly',
	'Decline Dumbbell Fly',
	'Cable Fly',
	'Standing Cable Fly',
	'Seated Cable Fly',
	'Mid Cable Fly',
	'Low to High Cable Fly',
	'High to Low Cable Fly',
	'Incline Cable Fly',
	'Decline Cable Fly',
	'Cable Press Around',
	'Cuffed Cable Chest Fly',
	'Cuffed Cable Press Around',
	'Lengthened Partial Pec Deck',
	'Lengthened Partial Cable Fly',

	// Shoulders
	'Standing Overhead Press',
	'Seated Overhead Press',
	'Barbell Shoulder Press',
	'Dumbbell Shoulder Press',
	'Seated Dumbbell Shoulder Press',
	'Machine Shoulder Press',
	'Smith Shoulder Press',
	'Bradford Press',
	'Z Press',
	'Behind the Neck Press',
	'Arnold Press',
	'Push Press',
	'Landmine Press',
	'High Incline Press',
	'Lateral Raise',
	'Standing Dumbbell Lateral Raise',
	'Seated Dumbbell Lateral Raise',
	'Leaning Dumbbell Lateral Raise',
	'Cable Lateral Raise',
	'Behind the Back Cable Lateral Raise',
	'Machine Lateral Raise',
	'Partial Lateral Raise',
	'Lengthened Partial Lateral Raise',
	'Lying Cable Lateral Raise',
	'Incline Lateral Raise',
	'Cuffed Cable Lateral Raise',
	'Cuffed Lying Cable Lateral Raise',
	'Front Raise',
	'Dumbbell Front Raise',
	'Plate Front Raise',
	'Cable Front Raise',
	'Cable Y Raise',
	'Scaption Raise',
	'Trap-3 Raise',
	'Prone Y Raise',
	'Prone T Raise',
	'Prone W Raise',
	'Lu Raise',
	'Upright Row',
	'Cable Upright Row',
	'Rear Delt Fly',
	'Bent Over Rear Delt Raise',
	'Reverse Pec Deck',
	'Rear Delt Machine',
	'Chest Supported Rear Delt Raise',
	'Cable Rear Delt Fly',
	'Chest Supported Reverse Fly',
	'Cable External Rotation',
	'Cable Internal Rotation',
	'Band External Rotation',
	'Band Internal Rotation',
	'Cuban Press',
	'90 90 External Rotation',
	'90 90 Internal Rotation',

	// Biceps / brachialis / brachioradialis
	'Barbell Curl',
	'Strict Curl',
	'Cheat Curl',
	'EZ Bar Curl',
	'Straight Bar Curl',
	'Cable Curl',
	'Straight Bar Cable Curl',
	'EZ Bar Cable Curl',
	'Dual Handle Cable Curl',
	'Machine Curl',
	'Machine Preacher Curl',
	'Standing Dumbbell Curl',
	'Alternating Dumbbell Curl',
	'Seated Dumbbell Curl',
	'Recline Dumbbell Curl',
	'30 Degree Recline Dumbbell Curl',
	'45 Degree Recline Dumbbell Curl',
	'60 Degree Recline Dumbbell Curl',
	'Recline Hammer Curl',
	'Recline Reverse Curl',
	'Preacher Curl',
	'30 Degree Preacher Curl',
	'45 Degree Preacher Curl',
	'60 Degree Preacher Curl',
	'75 Degree Preacher Curl',
	'Cable Preacher Curl',
	'Spider Curl',
	'Spider Hammer Curl',
	'Spider Reverse Curl',
	'High Cable Curl',
	'Low Cable Curl',
	'Lying Cable Curl',
	'Bayesian Cable Curl',
	'Drag Curl',
	'Hammer Curl',
	'Rope Hammer Curl',
	'Reverse Curl',
	'EZ Bar Reverse Curl',
	'Cable Reverse Curl',
	'Preacher Reverse Curl',
	'Preacher Hammer Curl',
	'Fat Grip Curl',
	'Fat Grip Hammer Curl',

	// Triceps
	'Skull Crusher',
	'EZ Bar Skull Crusher',
	'Dumbbell Skull Crusher',
	'Incline Skull Crusher',
	'Decline Skull Crusher',
	'Rolling Dumbbell Triceps Extension',
	'Lying Triceps Extension',
	'Cable Skull Crusher',
	'French Press',
	'Overhead Barbell Triceps Extension',
	'Overhead EZ Bar Triceps Extension',
	'PJR Pullover',
	'Close Grip Push-up',
	'Close Grip Smith Bench Press',
	'Cable Triceps Pushdown',
	'Straight Bar Pushdown',
	'EZ Bar Pushdown',
	'V Bar Pushdown',
	'Rope Pushdown',
	'Reverse Grip Pushdown',
	'Overhead Cable Triceps Extension',
	'Rope Overhead Triceps Extension',
	'EZ Bar Overhead Triceps Extension',
	'Dual Cable Katana Triceps Extension',
	'Bench Dip',
	'JM Press',
	'Tate Press',

	// Forearms / wrists / grip
	'Wrist Curl',
	'Reverse Wrist Curl',
	'Behind the Back Wrist Curl',
	'Barbell Wrist Flexion',
	'Barbell Wrist Extension',
	'Dumbbell Wrist Flexion',
	'Dumbbell Wrist Extension',
	'Finger Curl',
	'Reverse Finger Curl',
	'Barbell Pronation',
	'Barbell Supination',
	'Lever Bar Pronation',
	'Lever Bar Supination',
	'Wrist Roller Flexion',
	'Wrist Roller Extension',
	'Plate Pinch Hold',
	'Crush Grip Hold',

	// Neck
	'Neck Flexion',
	'Neck Extension',
	'Neck Lateral Flexion',
	'Neck Harness Extension',
	'Machine Neck Flexion',
	'Machine Neck Extension',
	'Machine Neck Lateral Flexion',

	// Legs
	'Back Squat',
	'High Bar Squat',
	'Low Bar Squat',
	'Front Squat',
	'Pause Squat',
	'Box Squat',
	'Anderson Squat',
	'Zercher Squat',
	'Safety Bar Squat',
	'Hatfield Squat',
	'Hack Squat',
	'Machine Hack Squat',
	'Pendulum Squat',
	'V Squat',
	'Lever Squat',
	'Belt Squat',
	'Goblet Squat',
	'Landmine Squat',
	'Smith Squat',
	'Heel Elevated Squat',
	'Smith Heel Elevated Squat',
	'Cyclist Squat',
	'Leg Press',
	'Narrow Stance Leg Press',
	'Wide Stance Leg Press',
	'High Foot Leg Press',
	'Low Foot Leg Press',
	'Hack Squat Toe Press',
	'Romanian Deadlift',
	'Deficit Romanian Deadlift',
	'Deadlift',
	'Conventional Deadlift',
	'Sumo Deadlift',
	'Trap Bar Deadlift',
	'Snatch Grip Deadlift',
	'Stiff Leg Deadlift',
	'Snatch Grip Romanian Deadlift',
	'Good Morning',
	'Smith Good Morning',
	'Machine Good Morning',
	'45 Degree Back Extension',
	'Weighted Back Extension',
	'Back Extension Glute Bias',
	'Reverse Hyperextension',
	'Glute Ham Raise',
	'Nordic Curl',
	'Reverse Nordic Curl',
	'Seated Leg Curl',
	'Lying Leg Curl',
	'Prone Leg Curl',
	'Leg Extension',
	'Sissy Squat',
	'Cable Sissy Squat',
	'Hip Thrust',
	'Barbell Glute Bridge',
	'Kas Glute Bridge',
	'Machine Hip Thrust',
	'Glute Drive',
	'Cable Pull Through',
	'Frog Pump',
	'Adductor Machine',
	'Abductor Machine',
	'Hip Adduction Machine',
	'Hip Abduction Machine',
	'Standing Calf Raise',
	'Smith Calf Raise',
	'Seated Calf Raise',
	'Donkey Calf Raise',
	'Leg Press Calf Raise',
	'Hack Squat Calf Raise',
	'Bent Knee Calf Raise',
	'Straight Leg Calf Raise',
	'Tibialis Raise',
	'Seated Tibialis Raise',
	'Tib Bar Raise',

	// Core / trunk
	'Cable Crunch',
	'Crunch',
	'Weighted Crunch',
	'Machine Crunch',
	'Decline Sit-up',
	'Sit-up',
	'Roman Chair Sit-up',
	'GHD Sit-up',
	'Hanging Knee Raise',
	'Hanging Leg Raise',
	'Hanging Straight Leg Raise',
	'Captains Chair Knee Raise',
	'Ab Wheel Rollout',
	'Barbell Rollout',
	'Plank',
	'Weighted Plank',
	'Reverse Crunch',
	'Cable Reverse Crunch',
	'Dead Bug',
	'Weighted Dead Bug',
	'Bird Dog',
	'Body Saw',
	'Stir the Pot',
	'Dragon Flag',
	'V-Up',
	'Toe Touch',
	'Cable Side Bend',
	'Machine Side Bend',
	'Hanging Oblique Knee Raise',
	'Hanging Windshield Wiper',
	'Copenhagen Plank',

	// Long-length / partial / cable-friendly
	'Lengthened Partial Leg Extension',
	'Lengthened Partial Leg Curl',
	'Lengthened Partial Calf Raise',
	'Lengthened Partial Curl',
	'Lengthened Partial Triceps Extension',
	'Lengthened Partial Pulldown',
	'Lengthened Partial Pullover'
];

const UNILATERAL_EXERCISE_NAMES = [
	// Pulling
	'Single Arm Lat Pulldown',
	'Single Arm Kneeling Lat Pulldown',
	'Single Arm Close Neutral Lat Pulldown',
	'Single Arm Supinated Lat Pulldown',
	'Single Arm MAG Grip Lat Pulldown',
	'Single Arm Straight Arm Pulldown',
	'Single Arm Straight Arm Pressdown',
	'Single Arm Cable Pullover',
	'Single Arm Machine Pullover',
	'Single Arm Dumbbell Pullover',
	'Single Arm Dumbbell Row',
	'Single Arm Bench Supported Dumbbell Row',
	'Single Arm Chest Supported Dumbbell Row',
	'Single Arm Chest Supported Machine Row',
	'Single Arm Machine Row',
	'Single Arm Iso Lateral Row',
	'Single Arm Cable Row',
	'Single Arm Rope Row',
	'Single Arm Upper Back Cable Row',
	'Single Arm Lat Bias Cable Row',
	'Single Arm High Row',
	'Single Arm Low Row',
	'Single Arm Landmine Row',
	'Meadows Row',
	'Single Arm Rear Delt Row',
	'Single Arm Face Pull',
	'Single Arm Rope Face Pull',
	'Single Arm Reverse Pec Deck',
	'Single Arm Rear Delt Machine',
	'Single Arm Scapular Pulldown',
	'Single Arm Shrug',
	'Unilateral Keenan Flap',
	'Unilateral Sagittal Keenan Flap',
	'Unilateral Frontal Keenan Flap',

	// Chest / pressing
	'Single Arm Cable Press',
	'Single Arm Machine Chest Press',
	'Single Arm Plate Loaded Chest Press',
	'Single Arm Dumbbell Bench Press',
	'Single Arm Incline Dumbbell Press',
	'Single Arm High Incline Dumbbell Press',
	'Single Arm Decline Dumbbell Press',
	'Single Arm Floor Press',
	'Single Arm Landmine Press',
	'Single Arm Push-up',
	'Single Arm Cable Fly',
	'Single Arm Standing Cable Fly',
	'Single Arm Mid Cable Fly',
	'Single Arm Low to High Cable Fly',
	'Single Arm High to Low Cable Fly',
	'Single Arm Incline Cable Fly',
	'Single Arm Decline Cable Fly',
	'Single Arm Cable Press Around',
	'Single Arm Cuffed Cable Chest Fly',
	'Single Arm Cuffed Cable Press Around',
	'Unilateral Pec Deck',
	'Single Arm Dumbbell Fly',

	// Shoulders
	'Single Arm Dumbbell Shoulder Press',
	'Single Arm Cable Shoulder Press',
	'Single Arm Machine Shoulder Press',
	'Single Arm Smith Shoulder Press',
	'Single Arm Landmine Press',
	'Single Arm Arnold Press',
	'Single Arm Z Press',
	'Single Arm Lateral Raise',
	'Single Arm Seated Lateral Raise',
	'Single Arm Leaning Dumbbell Lateral Raise',
	'Single Arm Cable Lateral Raise',
	'Single Arm Behind the Back Cable Lateral Raise',
	'Single Arm Leaning Cable Lateral Raise',
	'Single Arm Lying Cable Lateral Raise',
	'Single Arm Incline Lateral Raise',
	'Single Arm Cuffed Cable Lateral Raise',
	'Single Arm Cuffed Lying Cable Lateral Raise',
	'Single Arm Lengthened Partial Lateral Raise',
	'Single Arm Front Raise',
	'Single Arm Cable Front Raise',
	'Single Arm Rear Delt Fly',
	'Single Arm Bent Over Rear Delt Raise',
	'Single Arm Cable Rear Delt Fly',
	'Single Arm Reverse Pec Deck',
	'Single Arm Rear Delt Machine',
	'Single Arm Cable Y Raise',
	'Single Arm Trap-3 Raise',
	'Single Arm Prone Y Raise',
	'Single Arm Prone T Raise',
	'Single Arm Prone W Raise',
	'Single Arm Scaption Raise',
	'Single Arm Lu Raise',
	'Single Arm Upright Row',
	'Single Arm Cable External Rotation',
	'Single Arm Cable Internal Rotation',
	'Single Arm Band External Rotation',
	'Single Arm Band Internal Rotation',
	'Single Arm 90 90 External Rotation',
	'Single Arm 90 90 Internal Rotation',
	'Single Arm Side Lying External Rotation',

	// Biceps / brachialis / brachioradialis
	'Single Arm Dumbbell Curl',
	'Single Arm Alternating Dumbbell Curl',
	'Single Arm Cable Curl',
	'Single Arm Bayesian Cable Curl',
	'Single Arm High Cable Curl',
	'Single Arm Low Cable Curl',
	'Single Arm Lying Cable Curl',
	'Single Arm Cable Preacher Curl',
	'Single Arm Recline Dumbbell Curl',
	'Single Arm 30 Degree Recline Dumbbell Curl',
	'Single Arm 45 Degree Recline Dumbbell Curl',
	'Single Arm 60 Degree Recline Dumbbell Curl',
	'Single Arm Recline Hammer Curl',
	'Single Arm Recline Reverse Curl',
	'Single Arm Preacher Curl',
	'Single Arm Dumbbell Preacher Curl',
	'Single Arm 30 Degree Preacher Curl',
	'Single Arm 30 Degree Dumbbell Preacher Curl',
	'Single Arm 45 Degree Preacher Curl',
	'Single Arm 45 Degree Dumbbell Preacher Curl',
	'Single Arm 60 Degree Preacher Curl',
	'Single Arm 60 Degree Dumbbell Preacher Curl',
	'Single Arm 75 Degree Preacher Curl',
	'Single Arm 75 Degree Dumbbell Preacher Curl',
	'Single Arm Machine Preacher Curl',
	'Single Arm Spider Curl',
	'Single Arm Concentration Curl',
	'Single Arm Hammer Curl',
	'Single Arm Rope Hammer Curl',
	'Single Arm Cross Body Hammer Curl',
	'Single Arm Pinwheel Curl',
	'Single Arm Reverse Curl',
	'Single Arm Cable Reverse Curl',
	'Single Arm Reverse Preacher Curl',
	'Single Arm Drag Curl',
	'Single Arm Fat Grip Curl',

	// Triceps
	'Single Arm Cable Pushdown',
	'Single Arm Straight Bar Pushdown',
	'Single Arm Reverse Grip Pushdown',
	'Single Arm Overhead Cable Triceps Extension',
	'Single Arm Rope Overhead Triceps Extension',
	'Single Arm Cross Body Triceps Extension',
	'Single Arm Cable Kickback',
	'Single Arm Dumbbell Kickback',
	'Single Arm Katana Triceps Extension',
	'Single Arm Lying Triceps Extension',
	'Single Arm Dumbbell Skull Crusher',
	'Single Arm Rolling Dumbbell Triceps Extension',
	'Single Arm Cable Extension',
	'Single Arm Tate Press',

	// Forearms / wrists / grip
	'Single Arm Wrist Curl',
	'Single Arm Reverse Wrist Curl',
	'Single Arm Behind the Back Wrist Curl',
	'Single Arm Finger Curl',
	'Single Arm Reverse Finger Curl',
	'Single Arm Pronation',
	'Single Arm Supination',
	'Single Arm Lever Bar Pronation',
	'Single Arm Lever Bar Supination',
	'Single Arm Radial Deviation',
	'Single Arm Ulnar Deviation',
	'Single Arm Wrist Roller Flexion',
	'Single Arm Wrist Roller Extension',
	'Single Arm Plate Pinch Hold',

	// Neck
	'Single Side Neck Flexion',
	'Single Side Neck Extension',
	'Single Side Neck Lateral Flexion',

	// Legs
	'Bulgarian Split Squat',
	'Front Foot Elevated Split Squat',
	'Rear Foot Elevated Split Squat',
	'ATG Split Squat',
	'Split Squat',
	'Reverse Lunge',
	'Walking Lunge',
	'Forward Lunge',
	'Lateral Lunge',
	'Curtsy Lunge',
	'Deficit Reverse Lunge',
	'Step-up',
	'Lateral Step-up',
	'Poliquin Step-up',
	'Peterson Step-up',
	'Step-down',
	'Cossack Squat',
	'Pistol Squat',
	'Skater Squat',
	'Shrimp Squat',
	'Sprinter Squat',
	'Single Leg Box Squat',
	'Single Leg Smith Squat',
	'Single Leg Hack Squat',
	'Single Leg Leg Press',
	'B Stance Leg Press',
	'Single Leg Extension',
	'Single Leg Seated Leg Curl',
	'Single Leg Lying Leg Curl',
	'Single Leg Standing Leg Curl',
	'Cable Standing Leg Curl',
	'Single Leg Romanian Deadlift',
	'B Stance Romanian Deadlift',
	'Single Leg Good Morning',
	'Single Leg Hip Thrust',
	'B Stance Hip Thrust',
	'Single Leg Glute Bridge',
	'Single Leg Frog Pump',
	'Single Leg Back Extension',
	'Single Leg Reverse Hyperextension',
	'Cable Kickback',
	'Single Leg Calf Raise',
	'Single Leg Smith Calf Raise',
	'Single Leg Seated Calf Raise',
	'Single Leg Donkey Calf Raise',
	'Single Leg Leg Press Calf Raise',
	'Single Leg Tibialis Raise',
	'Cable Hip Flexion',
	'Cable Hip Extension',
	'Cable Hip Abduction',
	'Cable Hip Adduction',
	'Standing Cable Hip Internal Rotation',
	'Standing Cable Hip External Rotation',
	'Side Lying Hip Abduction',
	'Side Lying Hip Adduction',
	'Unilateral Adductor Machine',
	'Unilateral Abductor Machine',

	// Core / carries
	'Suitcase Carry',
	'Single Arm Farmer Carry',
	'Single Arm Rack Carry',
	'Single Arm Overhead Carry',
	'Pallof Press',
	'Half Kneeling Pallof Press',
	'Tall Kneeling Pallof Press',
	'Single Arm Cable Crunch',
	'Side Plank',
	'Weighted Side Plank',
	'Single Arm Plank',
	'Single Leg Plank',
	'Cable Wood Chop',
	'Cable Lift',
	'Cross Body Cable Chop',
	'Cross Body Cable Lift',
	'Copenhagen Side Plank',
	'Birddog Row',

	// Long-length / cable-friendly
	'Single Arm Lengthened Cable Curl',
	'Single Arm Lengthened Triceps Extension',
	'Single Arm Lengthened Cable Fly',
	'Single Arm Lengthened Pulldown',
	'Single Arm Lengthened Pullover'
];

const JOINT_ACTION_EXERCISE_NAMES = [
	// Bilateral upper body
	'Bilateral Vertical Pull',
	'Bilateral Vertical Press',
	'Bilateral Horizontal Pull',
	'Bilateral Horizontal Press',
	'Bilateral Sagittal Plane Pull',
	'Bilateral Sagittal Plane Press',
	'Bilateral Frontal Plane Pull',
	'Bilateral Frontal Plane Raise',
	'Bilateral Scapular Plane Raise',
	'Bilateral Shoulder Adduction',
	'Bilateral Shoulder Extension',
	'Bilateral Shoulder Flexion',
	'Bilateral Shoulder Abduction',
	'Bilateral Shoulder Horizontal Abduction',
	'Bilateral Shoulder Horizontal Adduction',
	'Bilateral Shoulder Internal Rotation',
	'Bilateral Shoulder External Rotation',
	'Bilateral Elbow Flexion',
	'Bilateral Elbow Extension',
	'Bilateral Wrist Flexion',
	'Bilateral Wrist Extension',
	'Bilateral Forearm Pronation',
	'Bilateral Forearm Supination',
	'Bilateral Scapular Depression',
	'Bilateral Scapular Elevation',
	'Bilateral Scapular Retraction',
	'Bilateral Scapular Protraction',

	// Bilateral lower body
	'Bilateral Hip Extension',
	'Bilateral Hip Flexion',
	'Bilateral Hip Abduction',
	'Bilateral Hip Adduction',
	'Bilateral Hip Internal Rotation',
	'Bilateral Hip External Rotation',
	'Bilateral Knee Extension',
	'Bilateral Knee Flexion',
	'Bilateral Plantar Flexion',
	'Bilateral Dorsiflexion',

	// Bilateral trunk / neck
	'Bilateral Trunk Flexion',
	'Bilateral Trunk Extension',
	'Bilateral Trunk Rotation',
	'Bilateral Trunk Lateral Flexion',
	'Bilateral Trunk Anti-Extension',
	'Bilateral Trunk Anti-Rotation',
	'Bilateral Trunk Anti-Lateral Flexion',
	'Bilateral Neck Flexion',
	'Bilateral Neck Extension',
	'Bilateral Neck Lateral Flexion',

	// Unilateral upper body
	'Single Arm Vertical Pull',
	'Single Arm Vertical Press',
	'Single Arm Horizontal Pull',
	'Single Arm Horizontal Press',
	'Single Arm Sagittal Plane Pull',
	'Single Arm Sagittal Plane Press',
	'Single Arm Frontal Plane Pull',
	'Single Arm Frontal Plane Raise',
	'Single Arm Scapular Plane Raise',
	'Single Arm Shoulder Adduction',
	'Single Arm Shoulder Extension',
	'Single Arm Shoulder Flexion',
	'Single Arm Shoulder Abduction',
	'Single Arm Shoulder Horizontal Abduction',
	'Single Arm Shoulder Horizontal Adduction',
	'Single Arm Shoulder Internal Rotation',
	'Single Arm Shoulder External Rotation',
	'Single Arm Elbow Flexion',
	'Single Arm Elbow Extension',
	'Single Arm Wrist Flexion',
	'Single Arm Wrist Extension',
	'Single Arm Forearm Pronation',
	'Single Arm Forearm Supination',
	'Single Arm Scapular Depression',
	'Single Arm Scapular Elevation',
	'Single Arm Scapular Retraction',
	'Single Arm Scapular Protraction',

	// Unilateral lower body
	'Single Leg Hip Extension',
	'Single Leg Hip Flexion',
	'Single Leg Hip Abduction',
	'Single Leg Hip Adduction',
	'Single Leg Hip Internal Rotation',
	'Single Leg Hip External Rotation',
	'Single Leg Knee Extension',
	'Single Leg Knee Flexion',
	'Single Leg Plantar Flexion',
	'Single Leg Dorsiflexion',

	// Unilateral trunk / neck
	'Single Side Trunk Flexion',
	'Single Side Trunk Extension',
	'Single Side Trunk Rotation',
	'Single Side Trunk Anti-Extension',
	'Single Side Trunk Anti-Rotation',
	'Single Side Trunk Anti-Lateral Flexion',
	'Single Side Neck Flexion',
	'Single Side Neck Extension',
	'Single Side Neck Lateral Flexion'
];

export const BILATERAL_EXERCISES = toEntries(BILATERAL_EXERCISE_NAMES, false);
export const UNILATERAL_EXERCISES = toEntries(UNILATERAL_EXERCISE_NAMES, true);

// Joint-action entries mix bilateral and unilateral labels, so infer from the name.
export const JOINT_ACTION_EXERCISES = [...new Set(JOINT_ACTION_EXERCISE_NAMES)].map((name) => ({
	name,
	unilateral:
		name.startsWith('Single Arm') ||
		name.startsWith('Single Leg') ||
		name.startsWith('Single Side') ||
		name.startsWith('Unilateral')
}));

export const BASELINE_EXERCISES = [
	...BILATERAL_EXERCISES,
	...UNILATERAL_EXERCISES,
	...JOINT_ACTION_EXERCISES
];
