# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  finishing_touches:
    docstrings:
      enabled: false
  pre_merge_checks:
    docstrings:
      mode: off
